version: '3.8'

services:
  backend:
    build: ./backend
    container_name: stl_backend
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-in-production}
      - FIREBIRD_HOST=host.docker.internal
      - FIREBIRD_PORT=3050
      - FIREBIRD_DATABASE=C:\\App\\STL\\Datos\\DATOS_STL.FDB
      - FIREBIRD_USER=${FIREBIRD_USER:-sysdba}
      - FIREBIRD_PASSWORD=${FIREBIRD_PASSWORD:-masterkey}
    volumes:
      - ./backend/app:/app/app
    depends_on:
      - frontend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: stl_frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - /app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

networks:
  default:
    driver: bridge