version: '3.8'

services:
  backend:
    build: ./backend
    container_name: stl_backend
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      # Para Windows, usar host.docker.internal para conectar a Firebird local
      - FIREBIRD_HOST=host.docker.internal
      - FIREBIRD_PORT=${FIREBIRD_PORT:-3050}
      - FIREBIRD_DATABASE=${FIREBIRD_DATABASE}
      - FIREBIRD_USER=${FIREBIRD_USER}
      - FIREBIRD_PASSWORD=${FIREBIRD_PASSWORD}
      - SAP_API_URL=${SAP_API_URL}
      - SAP_API_USERNAME=${SAP_API_USERNAME}
      - SAP_API_PASSWORD=${SAP_API_PASSWORD}
    volumes:
      - ./backend/app:/app/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # No necesario en Windows con Docker Desktop
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: stl_frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    depends_on:
      - backend

networks:
  default:
    driver: bridge