-- Archivo generado automáticamente desde pedido.json
-- Pedido: 1187 - Tipo: 201
-- Generado: 2025-07-10 18:41:50

-- INSERT para STL_DISPATCHES
INSERT INTO STL_DISPATCHES (
    NUMERO_DESPACHO,
    NUMERO_BUSQUEDA,
    FECHA_CREACION,
    FECHA_PICKING,
    FECHA_CARGA,
    CODIGO_CLIENTE,
    NOMBRE_CLIENTE,
    TIPO_DESPACHO,
    SYNC_STATUS,
    LAST_SYNC_AT
) VALUES (
    1187,
    1004,
    '2025-07-10',
    '2025-07-10',
    NULL,
    'CL-01016',
    'PLAYA GRANDE GOLF RESORT INC',
    201,
    'SYNCED',
    CURRENT_TIMESTAMP
);

-- INSERTs para STL_DISPATCH_LINES
-- Línea 1
INSERT INTO STL_DISPATCH_LINES (
    DISPATCH_ID,
    CODIGO_PRODUCTO,
    NOMBRE_PRODUCTO,
    ALMACEN,
    CANTIDAD_UMB,
    LINE_NUM,
    UOM_CODE,
    UOM_ENTRY
) VALUES (
    (SELECT ID FROM STL_DISPATCHES WHERE NUMERO_DESPACHO = 1187 AND TIPO_DESPACHO = 201),
    '44',
    'MUSLOS DE POLLO',
    '01',
    80,
    0,
    'Libra',
    2
);

-- Línea 2
INSERT INTO STL_DISPATCH_LINES (
    DISPATCH_ID,
    CODIGO_PRODUCTO,
    NOMBRE_PRODUCTO,
    ALMACEN,
    CANTIDAD_UMB,
    LINE_NUM,
    UOM_CODE,
    UOM_ENTRY
) VALUES (
    (SELECT ID FROM STL_DISPATCHES WHERE NUMERO_DESPACHO = 1187 AND TIPO_DESPACHO = 201),
    '98',
    'HAMBURGUESAS CAB 6 OZ',
    '01',
    24,
    1,
    'Libra',
    2
);

-- Línea 3
INSERT INTO STL_DISPATCH_LINES (
    DISPATCH_ID,
    CODIGO_PRODUCTO,
    NOMBRE_PRODUCTO,
    ALMACEN,
    CANTIDAD_UMB,
    LINE_NUM,
    UOM_CODE,
    UOM_ENTRY
) VALUES (
    (SELECT ID FROM STL_DISPATCHES WHERE NUMERO_DESPACHO = 1187 AND TIPO_DESPACHO = 201),
    '140',
    'TOCINETA NO. 1',
    '01',
    15,
    2,
    'Libra',
    2
);

-- Línea 4
INSERT INTO STL_DISPATCH_LINES (
    DISPATCH_ID,
    CODIGO_PRODUCTO,
    NOMBRE_PRODUCTO,
    ALMACEN,
    CANTIDAD_UMB,
    LINE_NUM,
    UOM_CODE,
    UOM_ENTRY
) VALUES (
    (SELECT ID FROM STL_DISPATCHES WHERE NUMERO_DESPACHO = 1187 AND TIPO_DESPACHO = 201),
    '28',
    'PECHUGA DE PAVO',
    '01',
    60,
    3,
    'Libra',
    2
);

-- Línea 5
INSERT INTO STL_DISPATCH_LINES (
    DISPATCH_ID,
    CODIGO_PRODUCTO,
    NOMBRE_PRODUCTO,
    ALMACEN,
    CANTIDAD_UMB,
    LINE_NUM,
    UOM_CODE,
    UOM_ENTRY
) VALUES (
    (SELECT ID FROM STL_DISPATCHES WHERE NUMERO_DESPACHO = 1187 AND TIPO_DESPACHO = 201),
    '466',
    'PECHUGA DE POLLO AMERICANA',
    '01',
    80,
    4,
    'Libra',
    2
);

-- Línea 6
INSERT INTO STL_DISPATCH_LINES (
    DISPATCH_ID,
    CODIGO_PRODUCTO,
    NOMBRE_PRODUCTO,
    ALMACEN,
    CANTIDAD_UMB,
    LINE_NUM,
    UOM_CODE,
    UOM_ENTRY
) VALUES (
    (SELECT ID FROM STL_DISPATCHES WHERE NUMERO_DESPACHO = 1187 AND TIPO_DESPACHO = 201),
    '192',
    'CARNE MOLIDA 80/20 CAB',
    '01',
    40,
    5,
    'Libra',
    2
);

-- Línea 7
INSERT INTO STL_DISPATCH_LINES (
    DISPATCH_ID,
    CODIGO_PRODUCTO,
    NOMBRE_PRODUCTO,
    ALMACEN,
    CANTIDAD_UMB,
    LINE_NUM,
    UOM_CODE,
    UOM_ENTRY
) VALUES (
    (SELECT ID FROM STL_DISPATCHES WHERE NUMERO_DESPACHO = 1187 AND TIPO_DESPACHO = 201),
    '37',
    'LOMO DE CERDO',
    '01',
    40,
    6,
    'Libra',
    2
);

-- FIN
