-- Agregar campos DATA_HASH para optimización de sincronización

-- Tabla STL_ITEMS
ALTER TABLE STL_ITEMS ADD DATA_HASH VARCHAR(32);

-- Tabla STL_DISPATCHES  
ALTER TABLE STL_DISPATCHES ADD DATA_HASH VARCHAR(32);

-- Tabla STL_GOODS_RECEIPTS
ALTER TABLE STL_GOODS_RECEIPTS ADD DATA_HASH VARCHAR(32);

-- Tabla STL_DISPATCH_LINES (para comparar líneas)
ALTER TABLE STL_DISPATCH_LINES ADD DATA_HASH VARCHAR(32);

-- Tabla STL_GOODS_RECEIPT_LINES (para comparar líneas)
ALTER TABLE STL_GOODS_RECEIPT_LINES ADD DATA_HASH VARCHAR(32);

COMMIT;