-- ========================================
-- CONSULTAS PARA VERIFICAR DATOS SAP-STL
-- ========================================

-- 1. Ver cuántos items hay sincronizados
SELECT COUNT(*) AS TOTAL_ITEMS FROM STL_ITEMS;

-- 2. Ver primeros 10 items
SELECT FIRST 10 
    ID,
    CODIGO_PRODUCTO,
    DESCRIPCION_PRODUCTO,
    CODIGO_FAMILIA,
    NOMBRE_FAMILIA,
    LAST_SYNC_AT,
    SYNC_STATUS
FROM STL_ITEMS
ORDER BY ID;

-- 3. Ver items por familia
SELECT 
    CODIGO_FAMILIA,
    NOMBRE_FAMILIA,
    COUNT(*) AS CANTIDAD
FROM STL_ITEMS
GROUP BY CODIGO_FAMILIA, NOMBRE_FAMILIA
ORDER BY CANTIDAD DESC;

-- 4. Ver despachos sincronizados
SELECT COUNT(*) AS TOTAL_DESPACHOS FROM STL_DISPATCHES;

-- 5. Ver últimos 10 despachos
SELECT FIRST 10
    ID,
    NUMERO_DESPACHO,
    TIPO_DESPACHO,
    FECHA_PICKING,
    CODIGO_CLIENTE,
    NOMBRE_CLIENTE,
    LAST_SYNC_AT
FROM STL_DISPATCHES
ORDER BY FECHA_PICKING DESC;

-- 6. Ver recepciones sincronizadas
SELECT COUNT(*) AS TOTAL_RECEPCIONES FROM STL_GOODS_RECEIPTS;

-- 7. Ver últimas 10 recepciones
SELECT FIRST 10
    ID,
    NUMERO_DOCUMENTO,
    TIPO_RECEPCION,
    FECHA,
    CODIGO_SUPLIDOR,
    NOMBRE_SUPLIDOR,
    LAST_SYNC_AT
FROM STL_GOODS_RECEIPTS
ORDER BY FECHA DESC;

-- 8. Ver estado de sincronización
SELECT 
    ENTITY_TYPE,
    SYNC_ENABLED,
    LAST_SYNC_AT,
    NEXT_SYNC_AT,
    SYNC_INTERVAL_MINUTES
FROM STL_SYNC_CONFIG
ORDER BY ENTITY_TYPE;

-- 9. Ver logs de sincronización recientes
SELECT FIRST 20
    ENTITY_TYPE,
    OPERATION,
    STATUS,
    ERROR_MESSAGE,
    SYNC_DATE,
    PROCESSING_TIME
FROM STL_SYNC_LOG
ORDER BY SYNC_DATE DESC;

-- 10. Resumen general
SELECT 
    'ITEMS' AS TIPO,
    COUNT(*) AS CANTIDAD,
    MAX(LAST_SYNC_AT) AS ULTIMA_SYNC
FROM STL_ITEMS
UNION ALL
SELECT 
    'DESPACHOS' AS TIPO,
    COUNT(*) AS CANTIDAD,
    MAX(LAST_SYNC_AT) AS ULTIMA_SYNC
FROM STL_DISPATCHES
UNION ALL
SELECT 
    'RECEPCIONES' AS TIPO,
    COUNT(*) AS CANTIDAD,
    MAX(LAST_SYNC_AT) AS ULTIMA_SYNC
FROM STL_GOODS_RECEIPTS;