-- ========================================
-- TABLA DE USUARIOS PARA AUTENTICACIÓN
-- ========================================

-- Crear generador para IDs de usuarios
CREATE GENERATOR GEN_USERS_ID;
SET GENERATOR GEN_USERS_ID TO 0;

-- Crear tabla de usuarios
CREATE TABLE USERS (
    ID INTEGER NOT NULL,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    EMAIL VARCHAR(100) NOT NULL,
    HASHED_PASSWORD VARCHAR(255) NOT NULL,
    IS_ACTIVE SMALLINT DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_USERS PRIMARY KEY (ID)
);

-- Crear trigger para auto-incremento
CREATE OR ALTER TRIGGER TR_USERS_BI FOR USERS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.ID IS NULL) THEN
        NEW.ID = GEN_ID(GEN_USERS_ID, 1);
END;

-- Crear índices
CREATE INDEX IDX_USERS_USERNAME ON USERS(USERNAME);
CREATE INDEX IDX_USERS_EMAIL ON USERS(EMAIL);

-- Insertar usuario por defecto (admin)
INSERT INTO USERS (USERNAME, EMAIL, HASHED_PASSWORD, IS_ACTIVE, CREATED_AT, UPDATED_AT) 
VALUES (
    'admin', 
    'admin@stl.com', 
    '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LzUp1hjJj9JG4D7zG', -- password: admin123
    1, 
    CURRENT_TIMESTAMP, 
    CURRENT_TIMESTAMP
);

COMMIT;